MAN-54-Compose-the-solution
cant0r/YouToddler pull request #27
Opened 2023-04-25 18:53 UTC by cant0r

2023-04-25 19:16 UTC, TheUsernameIsNotTaken requested changes

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on .github/workflows/pr-pipeline.yml
Yeah, I also think mac-os won't be used as a server.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on .nuke/build.schema.json
> +        "DOCKER_PASSWORD": {
Secrets good. This is the max I can get out of this.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on .nuke/build.schema.json
> +              "PublishAll",
New steps inside pipleline: Check.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on README.md
Updated readme: Check.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on build/Build.Constants.cs
Yeah, seems right.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
Can this be done in a way, that it uses the spring .pom version instead of a burned in value? I can check if it is unknown to us yet.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on docker-compose.yml
> +      - "9090:9090"
Yeah, port is ok.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on src/YouToddlerWebAPI/Dockerfile
Seems right. If this works, then it is ok.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on src/YouToddlerFrontend/Dockerfile
Seems ok, not mine.

2023-04-25 19:16 UTC, TheUsernameIsNotTaken commented on docker-compose.yml
Can the version be not fixed for the jar? I ask, because as I fast-checkid, removing the version form the file name during generation is not just a simple pom file change.
Or add a check/comment to this/that, to also update the other file if one changes. CAn do it, but let's fix it in next meeting.

2023-04-26 08:16 UTC, cant0r commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
Yeah, I found this ugly as well. I'm not sure how to resolve this. Any idea?

2023-04-26 08:27 UTC, TheUsernameIsNotTaken commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
Yeah, will try out with this: https://docs.docker.com/compose/environment-variables/set-environment-variables/

2023-04-26 09:01 UTC, TheUsernameIsNotTaken requested changes

2023-04-26 09:03 UTC, TheUsernameIsNotTaken commented on build/Build.cs
> +                .SetTag("youtoddler/backend:latest")
Or just export an API-VERSION env variable before running both commands. (build and then run)

2023-04-26 09:11 UTC, cant0r commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
That looks like a nice solution

2023-04-26 09:11 UTC, cant0r commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
Yeah, I'll add environment variables to the Docker build stages then. ty

2023-04-26 09:13 UTC, cant0r commented on build/Build.cs
> +                .SetTag("youtoddler/backend:latest")
The backend is made up by the CLI and the WebAPi, in order for Docker to have access to both of these a common root directory is needed. You cannot use "../" in Docker files. :)

2023-04-26 09:17 UTC, TheUsernameIsNotTaken commented on build/Build.cs
> +                .SetTag("youtoddler/backend:latest")
Yeah, thinked bacause I hoped an .env file would be enought, but later realised that the Powershell still runs in the API directory, so using 1 single is only solved, if you change that too.

2023-04-26 09:30 UTC, TheUsernameIsNotTaken commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
Started a new branch for it as https://github.com/cant0r/YouToddler/tree/MAN-55-Use-variables-in-version-control

2023-04-26 09:47 UTC, cant0r commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
Please make sure to target this MAN-54 target as the target of the PR you are going to open and not master. We'll have merge conflicts otherwise.

2023-04-26 11:23 UTC, szemand approved these changes

2023-04-26 11:33 UTC, TheUsernameIsNotTaken approved these changes

2023-04-26 11:36 UTC, merged