MAN-28-Create-GitHub-Actions-CI-pipelines-for-the-Frontend-SPA
cant0r/YouToddler pull request #28
Opened 2023-04-25 18:53 UTC by cant0r

2023-04-25 19:20 UTC, TheUsernameIsNotTaken requested changes
Version fixed in value is needed?

2023-04-25 19:20 UTC, TheUsernameIsNotTaken commented on .github/workflows/build-all-and-validate-nightly.yml
> +          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
Secrets Good.

2023-04-25 19:20 UTC, TheUsernameIsNotTaken commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
Yeah, this is what I in the last one. At least a comment will need to be added in my soruce code, but let's discuss it next meeting,

2023-04-26 09:05 UTC, TheUsernameIsNotTaken commented on docker-compose.yml
> +    command: java -jar youtoddler-spring-0.7.2.jar
Ok, is it ok if I try the changes mentioned #27 here first?

2023-04-26 11:19 UTC, TheUsernameIsNotTaken approved these changes

2023-04-26 11:22 UTC, szemand approved these changes

2023-04-26 11:32 UTC, merged